const fallback = {agents:[
  {id:'stellaris-advisor',name:'Stellaris Strategist',category:'Игровой советник',mode:'advisor',status:'active',initials:'ST'},
  {id:'desktop-copilot',name:'Desktop Copilot',category:'Компьютерный помощник',mode:'observer',status:'paused',initials:'DC'},
  {id:'factory-planner',name:'Factory Planner',category:'Satisfactory',mode:'assistant',status:'training',initials:'FP'}],logs:[]};
let state={...fallback,selected:null};
const api=async(method,...args)=>window.pywebview?.api?.[method]?window.pywebview.api[method](...args):null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function agentRow(a,card=false){return `<div class="${card?'agent-card':'agent-row'}" data-agent="${a.id}"><div class="agent-badge">${a.initials}</div><div><h3>${esc(a.name)}</h3><span>${esc(a.category)} · ${modeName(a.mode)}</span></div><span class="status ${a.status}">${a.status==='training'?'Обучение':'Готов'}</span></div>`}
function modeName(m){return ({observer:'Наблюдатель',advisor:'Советник',assistant:'Помощник',autonomous:'Автономный'})[m]||m}
function renderAgents(){ $('#agent-preview').innerHTML=state.agents.map(a=>agentRow(a)).join('');$('#agent-catalog').innerHTML=state.agents.map(a=>agentRow(a,true)).join('');$$('[data-agent]').forEach(x=>x.onclick=()=>openAgent(x.dataset.agent)); }
function renderActivity(){const logs=state.logs.slice(0,4);$('#activity-list').innerHTML=logs.length?logs.map(l=>`<div class="event"><i class="event-dot"></i><div><p>${esc(l.message)}</p><span>${esc(l.category)}</span></div><span>${new Date(l.timestamp).toLocaleTimeString('ru',{hour:'2-digit',minute:'2-digit'})}</span></div>`).join(''):`<div class="event"><i class="event-dot"></i><div><p>Рабочее пространство инициализировано</p><span>system.ready</span></div><span>сейчас</span></div>`}
function renderLogs(){const q=$('#log-search').value.toLowerCase(),level=$('#log-level').value;const list=state.logs.filter(l=>(!level||l.level===level)&&JSON.stringify(l).toLowerCase().includes(q));$('#log-list').innerHTML=list.length?list.map(l=>`<div class="log-entry"><span>${new Date(l.timestamp).toLocaleString('ru')}</span><span class="level ${l.level}">${l.level}</span><span><b>${esc(l.category)}</b><br>${esc(l.event)}</span><span>${esc(l.message)}</span></div>`).join(''):'<div style="padding:40px;text-align:center;color:var(--muted)">Событий по этому фильтру нет</div>'}
async function openAgent(id){state.selected=state.agents.find(a=>a.id===id);showPage('agents');$('#chat-empty').hidden=true;$('#chat').hidden=false;$('#chat-name').textContent=state.selected.name;$('#mode').value=state.selected.mode;$$('.agent-card').forEach(x=>x.classList.toggle('active',x.dataset.agent===id));const messages=await api('get_messages',id)||[];renderMessages(messages)}
function renderMessages(items){$('#messages').innerHTML=items.length?items.map(m=>`<div class="message ${m.role}">${esc(m.content)}<time>${new Date(m.created_at).toLocaleTimeString('ru',{hour:'2-digit',minute:'2-digit'})}</time></div>`).join(''):'<div class="empty"><p>Начните новый диалог. История этого агента хранится отдельно.</p></div>';$('#messages').scrollTop=$('#messages').scrollHeight}
const titles={overview:['Добрый вечер','Управляйте агентами, моделями и обучением в одном месте.'],agents:['ИИ-агенты','Общайтесь, ставьте задачи и выбирайте уровень автономности.'],logs:['Журнал событий','Чистые структурированные события без лишнего шума.'],models:['Модели','Базовые модели отделены от агентов и результатов обучения.'],trained:['Дообученные модели','Версии, метрики и контроль качества.'],training:['Обучение','Эксперименты, прогресс и автономные циклы улучшения.'],vision:['Машинное зрение','Источники экрана, OCR и распознавание интерфейса.'],voice:['Голос','Распознавание команд и синтез речи.'],sessions:['Игровые сессии','Тренировочные среды, эпизоды и награды.']};
function showPage(id){$$('.page').forEach(p=>p.classList.remove('active'));const actual=['overview','agents','logs'].includes(id)?id:'placeholder';$('#'+actual).classList.add('active');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===id));$('#page-title').textContent=titles[id][0];$('#page-subtitle').textContent=titles[id][1];if(actual==='placeholder')$('#placeholder-title').textContent=titles[id][0]+' — модуль подготовлен';if(id==='logs')renderLogs()}
async function init(){const data=await api('bootstrap');if(data)state={...state,...data};renderAgents();renderActivity();renderLogs()}
window.addEventListener('pywebviewready',init);setTimeout(()=>{if(!window.pywebview)init()},80);
$$('[data-page]').forEach(n=>n.onclick=()=>showPage(n.dataset.page));$$('[data-goto]').forEach(n=>n.onclick=()=>showPage(n.dataset.goto));
$('#theme').onclick=()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'':'dark';localStorage.setItem('feniks-theme',dark?'light':'dark')};if(localStorage.getItem('feniks-theme')==='dark')document.documentElement.dataset.theme='dark';
$('#composer').onsubmit=async e=>{e.preventDefault();const input=e.target.querySelector('textarea'),content=input.value.trim();if(!content)return;input.value='';const current=await api('get_messages',state.selected.id)||[];renderMessages([...current,{role:'user',content,created_at:new Date().toISOString()}]);const result=await api('send_message',state.selected.id,content);if(result?.ok){renderMessages([...current,...result.messages]);state.logs.unshift(result.log);renderActivity();toast('Задача добавлена в очередь')}else if(!window.pywebview){renderMessages([...current,{role:'user',content,created_at:new Date().toISOString()},{role:'assistant',content:'Демо-режим: подключите Python backend для выполнения задач.',created_at:new Date().toISOString()}])}};
$('#mode').onchange=async e=>{await api('set_agent_mode',state.selected.id,e.target.value);state.selected.mode=e.target.value;toast('Режим: '+modeName(e.target.value))};$('#refresh').onclick=async()=>{state.logs=await api('get_logs')||state.logs;renderActivity()};$('#log-search').oninput=renderLogs;$('#log-level').onchange=renderLogs;$('#new-agent').onclick=()=>{showPage('agents');toast('Конструктор агента будет доступен в следующем шаге')};
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
