let state={agents:[],logs:[],settings:{},selectedAgent:null,selectedChat:null,chats:[]};
const api=async(method,...args)=>window.pywebview?.api?.[method]?window.pywebview.api[method](...args):null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modeName=m=>({observer:'Наблюдатель',advisor:'Советник',assistant:'Помощник',autonomous:'Автономный'})[m]||m;
const categoryName=c=>({assistant:'Помощник',game:'Игровой агент',desktop:'Управление ПК',research:'Исследование',custom:'Другое'})[c]||c;
const initials=name=>name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function agentRow(a,card=false){return `<div class="${card?'agent-card':'agent-row'}" data-agent="${a.id}"><div class="agent-badge">${esc(initials(a.name))}</div><div><h3>${esc(a.name)}</h3><span>${esc(categoryName(a.category))} · ${esc(modeName(a.mode))}</span></div>${card?`<button class="row-delete" data-delete-agent="${a.id}" title="Удалить">×</button>`:`<span class="status">${a.chat_count||0} чат.</span>`}</div>`}
function renderAgents(){
  $('#agent-count').textContent=state.agents.length;$('#stat-agents').textContent=state.agents.length;$('#stat-chats').textContent=state.agents.reduce((n,a)=>n+(a.chat_count||0),0);$('#stat-events').textContent=state.logs.length;
  $('#agent-preview').innerHTML=state.agents.length?state.agents.slice(0,4).map(a=>agentRow(a)).join(''):'<div class="empty-inline">Агентов пока нет. Создайте первого агента.</div>';
  const query=$('#agent-search').value.trim().toLowerCase();const visible=state.agents.filter(a=>(a.name+' '+a.description+' '+categoryName(a.category)).toLowerCase().includes(query));
  $('#agent-catalog').innerHTML=visible.length?visible.map(a=>agentRow(a,true)).join(''):`<div class="empty catalog-empty"><span>◈</span><h3>${state.agents.length?'Ничего не найдено':'Список пуст'}</h3><p>${state.agents.length?'Измените поисковый запрос.':'Нажмите «Новый агент», чтобы начать.'}</p></div>`;
  $$('[data-agent]').forEach(x=>x.onclick=e=>{if(!e.target.closest('[data-delete-agent]'))openAgent(x.dataset.agent)});$$('[data-delete-agent]').forEach(x=>x.onclick=()=>removeAgent(x.dataset.deleteAgent));
}
function renderActivity(){const logs=state.logs.slice(0,4);$('#activity-list').innerHTML=logs.length?logs.map(l=>`<div class="event"><i class="event-dot"></i><div><p>${esc(l.message)}</p><span>${esc(l.category)} · ${esc(l.event)}</span></div><span>${new Date(l.timestamp).toLocaleTimeString('ru',{hour:'2-digit',minute:'2-digit'})}</span></div>`).join(''):'<div class="empty-inline">Событий пока нет</div>'}
function renderLogs(){const q=$('#log-search').value.toLowerCase(),level=$('#log-level').value;const list=state.logs.filter(l=>(!level||l.level===level)&&JSON.stringify(l).toLowerCase().includes(q));$('#log-list').innerHTML=list.length?list.map(l=>`<div class="log-entry"><span>${new Date(l.timestamp).toLocaleString('ru')}</span><span class="level ${l.level}">${l.level}</span><span><b>${esc(l.category)}</b><br>${esc(l.event)}</span><span>${esc(l.message)}</span></div>`).join(''):'<div class="empty-inline centered">Событий по этому фильтру нет</div>'}
async function openAgent(id){state.selectedAgent=state.agents.find(a=>a.id===id);if(!state.selectedAgent)return;showPage('agents');$('#chat-empty').hidden=true;$('#chat').hidden=false;$('#chat-name').textContent=state.selectedAgent.name;$('#mode').value=state.selectedAgent.mode;$$('.agent-card').forEach(x=>x.classList.toggle('active',x.dataset.agent===id));state.chats=await api('get_chats',id)||[];renderChatSelector();if(state.chats.length)await openChat(state.chats[0].id);else{$('#messages').innerHTML='<div class="empty"><span>▤</span><h3>Создайте первый чат</h3><p>Он станет отдельной вселенной этого агента.</p></div>';state.selectedChat=null}}
function renderChatSelector(){const select=$('#chat-select');select.innerHTML=state.chats.length?state.chats.map(c=>`<option value="${c.id}">${esc(c.title)} (${c.message_count})</option>`).join(''):'<option value="">Нет чатов</option>';if(state.selectedChat)select.value=state.selectedChat.id}
async function openChat(id){state.selectedChat=state.chats.find(c=>c.id===id);if(!state.selectedChat)return;renderChatSelector();renderMessages(await api('get_messages',id)||[])}
function renderMessages(items){$('#messages').innerHTML=items.length?items.map(m=>`<div class="message ${m.role}">${esc(m.content)}<time>${new Date(m.created_at).toLocaleString('ru')} · ${esc(m.status)}</time></div>`).join(''):'<div class="empty"><p>Чат пуст. Напишите первое сообщение.</p></div>';$('#messages').scrollTop=$('#messages').scrollHeight}
async function removeAgent(id){const agent=state.agents.find(a=>a.id===id);if(!agent||!confirm(`Удалить агента «${agent.name}» и все его чаты?`))return;const result=await api('delete_agent',id);if(result?.ok){state.agents=state.agents.filter(a=>a.id!==id);if(state.selectedAgent?.id===id){state.selectedAgent=null;$('#chat').hidden=true;$('#chat-empty').hidden=false}await reloadLogs();renderAgents();toast('Агент удалён')}}
const titles={overview:['Добрый вечер','Управляйте агентами, моделями и обучением в одном месте.'],agents:['ИИ-агенты','Независимые агенты, чаты и уровни автономности.'],logs:['Журнал событий','Структурированные события без лишнего шума.'],models:['Модели','Базовые модели отделены от агентов и результатов обучения.'],trained:['Дообученные модели','Версии, метрики и контроль качества.'],training:['Обучение','Эксперименты, прогресс и автономные циклы улучшения.'],vision:['Машинное зрение','Источники экрана, OCR и распознавание интерфейса.'],voice:['Голос','Распознавание команд и синтез речи.'],sessions:['Игровые сессии','Тренировочные среды, эпизоды и награды.']};
function showPage(id){$$('.page').forEach(p=>p.classList.remove('active'));const actual=['overview','agents','logs'].includes(id)?id:'placeholder';$('#'+actual).classList.add('active');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===id));$('#page-title').textContent=titles[id][0];$('#page-subtitle').textContent=titles[id][1];if(actual==='placeholder')$('#placeholder-title').textContent=titles[id][0]+' — следующий модуль';if(id==='logs')renderLogs()}
async function init(){const data=await api('bootstrap');if(!data){toast('Откройте интерфейс через python app.py');return}state={...state,...data};if(state.settings.theme==='dark')document.documentElement.dataset.theme='dark';renderAgents();renderActivity();renderLogs()}
async function reloadLogs(){state.logs=await api('get_logs')||state.logs;renderActivity();renderLogs()}
window.addEventListener('pywebviewready',init);$$('[data-page]').forEach(n=>n.onclick=()=>showPage(n.dataset.page));$$('[data-goto]').forEach(n=>n.onclick=()=>showPage(n.dataset.goto));
$$('[data-close]').forEach(button=>button.onclick=()=>$('#'+button.dataset.close).close());$('#agent-search').oninput=renderAgents;
$('#theme').onclick=async()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'':'dark';await api('save_setting','theme',dark?'light':'dark')};$('#new-agent').onclick=()=>$('#agent-dialog').showModal();
$('#agent-form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const result=await api('create_agent',data);if(!result?.ok)return toast(result?.error||'Не удалось создать агента');state.agents.unshift(result.agent);state.logs.unshift(result.log);e.target.reset();$('#agent-dialog').close();renderAgents();renderActivity();await openAgent(result.agent.id);toast('Агент создан и сохранён')};
$('#new-chat').onclick=()=>$('#chat-dialog').showModal();$('#chat-form').onsubmit=async e=>{e.preventDefault();if(!state.selectedAgent)return;const data=Object.fromEntries(new FormData(e.target));const parent=data.inherit_mode==='copy'?state.selectedChat?.id:null;const result=await api('create_chat',state.selectedAgent.id,data.title,parent,data.inherit_mode);if(!result?.ok)return toast(result?.error||'Не удалось создать чат');state.chats.unshift(result.chat);state.selectedAgent.chat_count=(state.selectedAgent.chat_count||0)+1;$('#chat-dialog').close();renderAgents();await openChat(result.chat.id);await reloadLogs();toast('Новая вселенная создана')};
$('#chat-select').onchange=e=>openChat(e.target.value);$('#delete-chat').onclick=async()=>{if(!state.selectedChat||!confirm(`Удалить чат «${state.selectedChat.title}»?`))return;const result=await api('delete_chat',state.selectedChat.id);if(result?.ok){state.chats=state.chats.filter(c=>c.id!==state.selectedChat.id);state.selectedAgent.chat_count=Math.max(0,(state.selectedAgent.chat_count||1)-1);state.selectedChat=null;renderAgents();renderChatSelector();if(state.chats.length)openChat(state.chats[0].id);else renderMessages([]);toast('Чат удалён')}};
$('#composer').onsubmit=async e=>{e.preventDefault();if(!state.selectedChat)return toast('Сначала создайте чат');const input=e.target.querySelector('textarea'),content=input.value.trim();if(!content)return;const result=await api('send_message',state.selectedAgent.id,state.selectedChat.id,content);if(!result?.ok)return toast(result?.error||'Ошибка сохранения');input.value='';renderMessages(await api('get_messages',state.selectedChat.id)||[]);state.logs.unshift(result.log);renderActivity();toast(result.model_status==='ready'?'Ответ модели получен':(result.error||'Сообщение сохранено'))};
$('#mode').onchange=async e=>{const result=await api('set_agent_mode',state.selectedAgent.id,e.target.value);if(result?.ok){state.selectedAgent.mode=e.target.value;renderAgents();toast('Режим сохранён: '+modeName(e.target.value))}else toast(result?.error)};$('#refresh').onclick=reloadLogs;$('#log-search').oninput=renderLogs;$('#log-level').onchange=renderLogs;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500)}

$('#model-settings').onclick=()=>{const f=$('#settings-form');for(const key of ['model_provider','model_base_url','model_name','model_api_key'])f.elements[key].value=state.settings[key]||'';$('#settings-dialog').showModal()};
$('#settings-form').onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));for(const [key,value] of Object.entries(values)){const result=await api('save_setting',key,value);if(!result?.ok)return toast(result?.error||'Ошибка сохранения')}state.settings={...state.settings,...values};$('#settings-dialog').close();toast('Настройки модели сохранены')};
